Repository chreden/trview, pull requests merged in 2018-11, with the labels that each got.

#375 Add support for Tomb Raider 5 levels
  README.md
  trlevel/Level.cpp
  trlevel/trtypes.cpp
  trlevel/trtypes.h
  trview.app/Mesh.cpp
  trview.app/Mesh.h
  trview/MeshStorage.cpp
  trview/Room.cpp
  trview/Room.h
Labels: TR5, enhancement, fexinspect, quality of life, speedrun planning

#377 Add item names for TR5
  trview/resources/type_names.txt
Labels: quality of life, speedrun planning

#383 Move numericupdown event out of set_value
  trview.ui/NumericUpDown.cpp
Labels: bug

#380 Improve the triggers filter
  trview.ui.render/Renderer.cpp
  trview.ui/Control.cpp
  trview.ui/Control.h
  trview.ui/Dropdown.cpp
  trview.ui/Dropdown.h
Labels: quality of life

#378 Convert settings object to json
  trlevel/Level.cpp
  trlevel/Level.h
  trlevel/trlevel.cpp
  trlevel/trlevel.h
  trview.app.tests/FileDropperTests.cpp
  trview.app.tests/RecentFilesTests.cpp
  trview.app/FileDropper.cpp
  trview.app/FileDropper.h
  trview.app/RecentFiles.cpp
  trview.app/RecentFiles.h
  trview.common/Strings.cpp
  trview.common/Strings.h
  trview.common/trview.common.vcxproj
  trview.common/trview.common.vcxproj.filters
  trview/DirectoryListing.cpp
  trview/DirectoryListing.h
  trview/LevelInfo.cpp
  trview/LevelInfo.h
  trview/LevelSwitcher.cpp
  trview/LevelSwitcher.h
  trview/UserSettings.cpp
  trview/UserSettings.h
  trview/Viewer.cpp
  trview/Viewer.h
  trview/trview.cpp
Labels: refactoring

#384 Set the window title to the current level
  trview.common/Window.cpp
  trview.common/Window.h
  trview/Viewer.cpp
Labels: quality of life

#381 Create version 1.0.10
  trview/Controls.txt
  trview/trview.rc
Labels: documentation

#385 Add support for controlling alternate groups
  trview.ui.render/RenderNode.h
  trview.ui.render/Renderer.cpp
  trview/Flipmaps.cpp
  trview/Flipmaps.h
  trview/Level.cpp
  trview/Level.h
  trview/Room.cpp
  trview/Room.h
  trview/RoomNavigator.cpp
  trview/RoomNavigator.h
  trview/Viewer.cpp
  trview/Viewer.h
  trview/trview.vcxproj
  trview/trview.vcxproj.filters
Labels: TR4, enhancement, quality of life, speedrun planning

#387 Take transparent triangles into account for bb generation
  trview.app/Mesh.cpp
Labels: bug

#392 Stop excessive GPU usage when minimised
  trview/Viewer.cpp
Labels: bug, performance

#394 Show no-space squares on the minimap
  trview.ui.render/MapRenderer.cpp
Labels: TR2, speedrun planning

#396 Change item/trigger windows to be hidden by default
  trview/UserSettings.h
Labels: quality of life

#398 Refactor the camera classes
  trview.app.tests/FreeCameraTests.cpp
  trview.app.tests/OrbitCameraTests.cpp
  trview.app.tests/StringConversions.cpp
  trview.app.tests/StringConversions.h
  trview.app.tests/trview.app.tests.vcxproj
  trview.app.tests/trview.app.tests.vcxproj.filters
  trview.app/Camera.cpp
  trview.app/Camera.h
  trview.app/Compass.h
  trview.app/FreeCamera.cpp
  trview.app/FreeCamera.h
  trview.app/ICamera.h
  trview.app/OrbitCamera.cpp
  trview.app/OrbitCamera.h
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
  trview/CameraMode.cpp
  trview/CameraMode.h
  trview/FreeCamera.cpp
  trview/FreeCamera.h
  trview/Viewer.h
  trview/trview.vcxproj
  trview/trview.vcxproj.filters
Labels: refactoring
