Repository chreden/trview, pull requests merged in 2018-07, with the labels that each got.

#241 Add SpriteFont headers, source and generator to DirectXTK
  external/DirectXTK/DirectXTK_Desktop_2017.vcxproj
  external/DirectXTK/DirectXTK_Desktop_2017.vcxproj.filters
  external/DirectXTK/Inc/CommonStates.h
  external/DirectXTK/Inc/GraphicsMemory.h
  external/DirectXTK/Inc/SpriteBatch.h
  external/DirectXTK/Inc/SpriteFont.h
  external/DirectXTK/Inc/VertexTypes.h
  external/DirectXTK/MakeSpriteFont/BitmapImporter.cs
  external/DirectXTK/MakeSpriteFont/BitmapUtils.cs
  external/DirectXTK/MakeSpriteFont/CharacterRegion.cs
  external/DirectXTK/MakeSpriteFont/CommandLineOptions.cs
  external/DirectXTK/MakeSpriteFont/CommandLineParser.cs
  external/DirectXTK/MakeSpriteFont/Glyph.cs
  external/DirectXTK/MakeSpriteFont/GlyphCropper.cs
  external/DirectXTK/MakeSpriteFont/GlyphPacker.cs
  external/DirectXTK/MakeSpriteFont/IFontImporter.cs
  external/DirectXTK/MakeSpriteFont/MakeSpriteFont.csproj
  external/DirectXTK/MakeSpriteFont/Program.cs
  external/DirectXTK/MakeSpriteFont/Properties/AssemblyInfo.cs
  external/DirectXTK/MakeSpriteFont/SpriteFontWriter.cs
  external/DirectXTK/MakeSpriteFont/TrueTypeImporter.cs
  external/DirectXTK/Src/AlignedNew.h
  external/DirectXTK/Src/BinaryReader.cpp
  external/DirectXTK/Src/BinaryReader.h
  external/DirectXTK/Src/ConstantBuffer.h
  external/DirectXTK/Src/GraphicsMemory.cpp
  external/DirectXTK/Src/Shaders/Compiled/SpriteEffect_SpritePixelShader.inc
  external/DirectXTK/Src/Shaders/Compiled/SpriteEffect_SpriteVertexShader.inc
  external/DirectXTK/Src/SharedResourcePool.h
  external/DirectXTK/Src/SpriteBatch.cpp
  external/DirectXTK/Src/SpriteFont.cpp
  trview.sln
Labels: bug

#243 Add missing DirectXTK common files
  external/DirectXTK/DirectXTK_Desktop_2017.vcxproj
  external/DirectXTK/DirectXTK_Desktop_2017.vcxproj.filters
  external/DirectXTK/Src/CommonStates.cpp
  external/DirectXTK/Src/DemandCreate.h
  external/DirectXTK/Src/VertexTypes.cpp
Labels: bug

#244 Use SpriteFont from DirectXTK instead of Direct2D/DirectWrite interop with D3D11
  trview.graphics/Font.cpp
  trview.graphics/Font.h
  trview.graphics/FontFactory.cpp
  trview.graphics/FontFactory.h
  trview.graphics/FontTexture.h
  trview.graphics/ParagraphAlignment.h
  trview.graphics/TextAlignment.h
  trview.graphics/trview.graphics.vcxproj
  trview.graphics/trview.graphics.vcxproj.filters
  trview.ui.render/LabelNode.cpp
  trview.ui.render/LabelNode.h
  trview.ui.render/Renderer.cpp
  trview.ui.render/Renderer.h
  trview.ui/Button.cpp
  trview.ui/Checkbox.cpp
  trview.ui/GroupBox.cpp
  trview.ui/Label.cpp
  trview.ui/Label.h
  trview.ui/NumericUpDown.cpp
  trview.ui/trview.ui.vcxproj
  trview.ui/trview.ui.vcxproj.filters
  trview/CameraControls.cpp
  trview/DefaultFonts.cpp
  trview/DefaultFonts.h
  trview/GoToRoom.cpp
  trview/LevelInfo.cpp
  trview/RoomNavigator.cpp
  trview/SettingsWindow.cpp
  trview/TextureWindow.cpp
  trview/Viewer.cpp
  trview/Viewer.h
  trview/fontlist.txt
  trview/resource.h
  trview/resources/arial8.bin
  trview/trview.rc
  trview/trview.vcxproj
  trview/trview.vcxproj.filters
Labels: bug

#246 Update version to 1.0.7
  trview/trview.rc
Labels: documentation

#247 Reposition the 'go to room' window when the parent resizes
  trview/GoToRoom.cpp
Labels: bug

#248 Add a shortcut to open a file
  trview/resource.h
  trview/trview.cpp
  trview/trview.rc
Labels: quality of life

#252 Split Device class up to allow for rendering to multiple windows
  trview.app/WindowResizer.cpp
  trview.app/WindowResizer.h
  trview.common/Size.cpp
  trview.common/Size.h
  trview.common/Window.cpp
  trview.common/Window.h
  trview.graphics/Device.cpp
  trview.graphics/Device.h
  trview.graphics/DeviceWindow.cpp
  trview.graphics/DeviceWindow.h
  trview.graphics/RenderTarget.cpp
  trview.graphics/RenderTarget.h
  trview.graphics/Sprite.cpp
  trview.graphics/Sprite.h
  trview.graphics/SpriteSizeStore.cpp
  trview.graphics/SpriteSizeStore.h
  trview.graphics/trview.graphics.vcxproj
  trview.graphics/trview.graphics.vcxproj.filters
  trview.ui.render/ButtonNode.cpp
  trview.ui.render/ImageNode.cpp
  trview.ui.render/MapRenderer.cpp
  trview.ui.render/MapRenderer.h
  trview.ui.render/RenderNode.cpp
  trview.ui.render/Renderer.cpp
  trview.ui.render/Renderer.h
  trview/Camera.cpp
  trview/Camera.h
  trview/FreeCamera.cpp
  trview/FreeCamera.h
  trview/Viewer.cpp
  trview/Viewer.h
Labels: quality of life, refactoring, speedrun planning

#255 Fix zoom changing when not in Orbit mode
  trview/Viewer.cpp
Labels: bug
