Repository chreden/trview, pull requests merged in 2020-05, with the labels that each got.

#649 Create Rooms Window
  trlevel/trtypes.h
  trview.app/Elements/Level.cpp
  trview.app/Elements/Level.h
  trview.app/Settings/UserSettings.cpp
  trview.app/Settings/UserSettings.h
  trview.app/UI/SettingsWindow.cpp
  trview.app/UI/SettingsWindow.h
  trview.app/UI/ViewerUI.cpp
  trview.app/Windows/CollapsiblePanel.cpp
  trview.app/Windows/CollapsiblePanel.h
  trview.app/Windows/RoomsWindow.cpp
  trview.app/Windows/RoomsWindow.h
  trview.app/Windows/RoomsWindowManager.cpp
  trview.app/Windows/RoomsWindowManager.h
  trview.app/Windows/WindowIDs.h
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
  trview.graphics/DeviceWindow.cpp
  trview.graphics/DeviceWindow.h
  trview.graphics/Texture.cpp
  trview.graphics/Texture.h
  trview.ui.render/MapRenderer.cpp
  trview.ui.render/MapRenderer.h
  trview.ui/Input.cpp
  trview.ui/Input.h
  trview.ui/Listbox.cpp
  trview.ui/Listbox.h
  trview.ui/Scrollbar.cpp
  trview/Viewer.cpp
  trview/Viewer.h
  trview/resource.h
  trview/trview.rc
Labels: quality of life, speedrun planning

#651 Give Group Box a built-in child area
  trview.app/Elements/Sector.cpp
  trview.app/UI/CameraControls.cpp
  trview.app/UI/GoTo.cpp
  trview.app/UI/RoomNavigator.cpp
  trview.app/UI/ViewOptions.cpp
  trview.app/Windows/ItemsWindow.cpp
  trview.app/Windows/RoomsWindow.cpp
  trview.app/Windows/RouteWindow.cpp
  trview.app/Windows/TriggersWindow.cpp
  trview.ui/Control.cpp
  trview.ui/Control.h
  trview.ui/GroupBox.cpp
  trview.ui/GroupBox.h
Labels: refactoring

#652 Tweaks for background colour dialog
  trview.app/Menus/ViewMenu.cpp
Labels: quality of life

#653 Hide measure label when behind camera
  trview.app/Tools/Measure.cpp
  trview.app/Windows/CollapsiblePanel.cpp
Labels: bug, speedrun planning

#656 Add 'outside' flag to room window display
  trview.app/Elements/Room.cpp
  trview.app/Elements/Room.h
  trview.app/Windows/RoomsWindow.cpp
Labels: speedrun planning

#658 Use yBottom instead of Y in the room window
  trview.app/Windows/RoomsWindow.cpp
Labels: bug

#659 Add new "Flipmaps" filter to the triggers window
  trview.app/Elements/Trigger.cpp
  trview.app/Elements/Trigger.h
  trview.app/Windows/TriggersWindow.cpp
  trview.app/Windows/TriggersWindow.h
Labels: speedrun planning

#662 Show booleans in rooms window as true/false instead of 1/0
  trview.app/Windows/ItemsWindow.cpp
  trview.app/Windows/RoomsWindow.cpp
  trview.app/Windows/TriggersWindow.cpp
  trview.common/Strings.cpp
  trview.common/Strings.h
Labels: bug, quality of life

#664 Revert "Stop adding X and Y coordinate value to UVs (#645)"
  trview.app/Graphics/LevelTextureStorage.cpp
Labels: bug
