Repository chreden/trview, pull requests merged in 2021-01, with the labels that each got.

#723 Fix warnings from external projects, internal warnings and switch back to non-DLL runtime
  external/DirectXTK/DirectXTK_Desktop_2017.vcxproj
  external/lua/lua.vcxproj
  external/lua/lua.vcxproj.filters
  external/lua/src/lua.c
  external/lua/src/luac.c
  external/zlib/contrib/vstudio/vc14/zlibstat.vcxproj
  trlevel/Level.cpp
  trlevel/trlevel.vcxproj
  trview.app.tests/trview.app.tests.vcxproj
  trview.app/Elements/Level.cpp
  trview.app/Elements/Room.cpp
  trview.app/Menus/UpdateChecker.cpp
  trview.app/Routing/Route.cpp
  trview.app/trview.app.vcxproj
  trview.common.tests/trview.common.tests.vcxproj
  trview.common/Strings.cpp
  trview.common/Windows/Shortcuts.cpp
  trview.common/trview.common.vcxproj
  trview.graphics.tests/trview.graphics.tests.vcxproj
  trview.graphics/Texture.cpp
  trview.graphics/trview.graphics.vcxproj
  trview.input.tests/trview.input.tests.vcxproj
  trview.input/trview.input.vcxproj
  trview.lau/drm.cpp
  trview.lau/trview.lau.vcxproj
  trview.tests.common/trview.tests.common.vcxproj
  trview.ui.render/trview.ui.render.vcxproj
  trview.ui.tests/ListboxTests.cpp
  trview.ui.tests/trview.ui.tests.vcxproj
  trview.ui/Control.cpp
  trview.ui/Grid.cpp
  trview.ui/Listbox.cpp
  trview.ui/ListboxRow.cpp
  trview.ui/TextArea.cpp
  trview.ui/trview.ui.vcxproj
  trview/Viewer.cpp
  trview/trview.vcxproj
Labels: build, refactoring

#728 Basic lua functionality
  Lua.md
  trview.app/Lua/Lua.cpp
  trview.app/Lua/Lua.h
  trview/Viewer.cpp
  trview/Viewer.h
  trview/ViewerLuaRegistry.cpp
  trview/trview.vcxproj
  trview/trview.vcxproj.filters
Labels: documentation, scripting

#732 Notify owned windows to resize when the main window is restored
  trview.app.tests/WindowResizerTests.cpp
  trview.app/Windows/WindowResizer.cpp
  trview.app/Windows/WindowResizer.h
  trview.tests.common/Window.cpp
  trview.tests.common/Window.h
Labels: bug, quality of life, ui

#731 Add room relative coordinates to route window
  trview.app/Windows/RouteWindow.cpp
  trview.app/Windows/RouteWindow.h
  trview.app/Windows/RouteWindowManager.cpp
  trview.app/Windows/RouteWindowManager.h
  trview/Viewer.cpp
Labels: quality of life
