Repository chreden/trview, pull requests merged in 2023-01, with the labels that each got.

#1086 Docs and shortcut for Camera/Sink, drop portal inferred room if possible
  README.md
  doc/camera-sink.png
  trview.app.tests/CameraSinkWindowManagerTests.cpp
  trview.app/ApplicationCreate.cpp
  trview.app/Elements/ILevel.h
  trview.app/Elements/Level.cpp
  trview.app/Elements/Level.h
  trview.app/Mocks/Elements/ILevel.h
  trview.app/Resources/trview.app.rc
  trview.app/Windows/CameraSink/CameraSinkWindow.cpp
  trview.app/Windows/CameraSink/CameraSinkWindowManager.cpp
  trview.app/Windows/CameraSink/CameraSinkWindowManager.h
  trview.app/Windows/Viewer.cpp
  trview.app/Windows/Viewer.h
Labels: quality of life

#1090 Show lights and camera/sinks in the rooms window
  trview.app.tests/ApplicationTests.cpp
  trview.app.tests/CameraSinkWindowTests.cpp
  trview.app.tests/ItemsWindowTests.cpp
  trview.app.tests/RoomsWindowManagerTests.cpp
  trview.app.tests/TestImgui.cpp
  trview.app.tests/TestImgui.h
  trview.app.tests/TriggersWindowTests.cpp
  trview.app.tests/Windows/LightsWindowTests.cpp
  trview.app/Application.cpp
  trview.app/Elements/IRoom.h
  trview.app/Elements/Room.cpp
  trview.app/Elements/Room.h
  trview.app/Mocks/Elements/IRoom.h
  trview.app/Mocks/Windows/IRoomsWindow.h
  trview.app/Mocks/Windows/IRoomsWindowManager.h
  trview.app/Track/Track.h
  trview.app/Track/Track.inl
  trview.app/Type.h
  trview.app/Type.inl
  trview.app/Windows/CameraSink/CameraSinkWindow.cpp
  trview.app/Windows/CameraSink/CameraSinkWindow.h
  trview.app/Windows/IRoomsWindow.h
  trview.app/Windows/IRoomsWindowManager.h
  trview.app/Windows/ItemsWindow.cpp
  trview.app/Windows/ItemsWindow.h
  trview.app/Windows/LightsWindow.cpp
  trview.app/Windows/LightsWindow.h
  trview.app/Windows/RoomsWindow.cpp
  trview.app/Windows/RoomsWindow.h
  trview.app/Windows/RoomsWindowManager.cpp
  trview.app/Windows/RoomsWindowManager.h
  trview.app/Windows/TriggersWindow.cpp
  trview.app/Windows/TriggersWindow.h
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
  trview.common/Algorithms.h
  trview.common/Algorithms.hpp
Labels: quality of life

#1092 Stop minimap from taking mouse input when obscured
  trview.app.tests/Windows/ViewerTests.cpp
  trview.app/Mocks/UI/IMapRenderer.h
  trview.app/UI/IMapRenderer.h
  trview.app/UI/MapRenderer.cpp
  trview.app/UI/MapRenderer.h
  trview.app/UI/ViewerUI.cpp
  trview.app/Windows/RoomsWindow.cpp
  trview.app/Windows/Viewer.cpp
Labels: bug, ui

#1093 Add Lua bindings for Level
  README.md
  doc/lua/index.md
  doc/lua/level.md
  doc/lua/trview.md
  trview.app.tests/Lua/Elements/Lua_LevelTests.cpp
  trview.app.tests/trview.app.tests.vcxproj
  trview.app.tests/trview.app.tests.vcxproj.filters
  trview.app/Application.cpp
  trview.app/Lua/Elements/Level/Lua_Level.cpp
  trview.app/Lua/Elements/Level/Lua_Level.h
  trview.app/Lua/Lua.cpp
  trview.app/Lua/Lua.h
  trview.app/Lua/trview/trview.cpp
  trview.app/Lua/trview/trview.h
  trview.app/UI/Console.cpp
  trview.app/UI/Console.h
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
Labels: scripting

#1097 Add Lua bindings for Item
  doc/lua/index.md
  doc/lua/item.md
  doc/lua/level.md
  doc/lua/room.md
  doc/lua/trigger.md
  doc/lua/vector3.md
  trview.app.tests/Lua/Elements/Lua_ItemTests.cpp
  trview.app.tests/Lua/Elements/Lua_LevelTests.cpp
  trview.app.tests/Lua/Elements/Lua_RoomTests.cpp
  trview.app.tests/Lua/Elements/Lua_TriggerTests.cpp
  trview.app.tests/trview.app.tests.vcxproj
  trview.app.tests/trview.app.tests.vcxproj.filters
  trview.app/Application.cpp
  trview.app/Application.h
  trview.app/ApplicationCreate.cpp
  trview.app/Elements/IItem.h
  trview.app/Elements/ILevel.h
  trview.app/Elements/IRoom.h
  trview.app/Elements/ITrigger.h
  trview.app/Elements/Item.cpp
  trview.app/Elements/Item.h
  trview.app/Elements/Level.cpp
  trview.app/Elements/Level.h
  trview.app/Elements/Room.cpp
  trview.app/Elements/Room.h
  trview.app/Elements/Trigger.cpp
  trview.app/Elements/Trigger.h
  trview.app/Lua/Elements/Item/Lua_Item.cpp
  trview.app/Lua/Elements/Item/Lua_Item.h
  trview.app/Lua/Elements/Level/Lua_Level.cpp
  trview.app/Lua/Elements/Level/Lua_Level.h
  trview.app/Lua/Elements/Room/Lua_Room.cpp
  trview.app/Lua/Elements/Room/Lua_Room.h
  trview.app/Lua/Elements/Trigger/Lua_Trigger.cpp
  trview.app/Lua/Elements/Trigger/Lua_Trigger.h
  trview.app/Lua/Lua.cpp
  trview.app/Lua/Lua.h
  trview.app/Lua/Lua.inl
  trview.app/Lua/Vector3.cpp
  trview.app/Lua/Vector3.h
  trview.app/Lua/trview/trview.cpp
  trview.app/Lua/trview/trview.h
  trview.app/Mocks/Elements/IItem.h
  trview.app/Mocks/Elements/ILevel.h
  trview.app/Mocks/Elements/IRoom.h
  trview.app/Mocks/Elements/ITrigger.h
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
  trview.sln
Labels: scripting

#1102 Add Lua bindings for Trigger
  doc/lua/camera_sink.md
  doc/lua/command.md
  doc/lua/level.md
  doc/lua/room.md
  doc/lua/sector.md
  doc/lua/trigger.md
  trview.app.tests/Lua/Elements/Lua_RoomTests.cpp
  trview.app.tests/Lua/Elements/Lua_SectorTests.cpp
  trview.app.tests/Lua/Elements/Lua_TriggerTests.cpp
  trview.app.tests/trview.app.tests.vcxproj
  trview.app.tests/trview.app.tests.vcxproj.filters
  trview.app/Lua/Elements/CameraSink/Lua_CameraSink.cpp
  trview.app/Lua/Elements/CameraSink/Lua_CameraSink.h
  trview.app/Lua/Elements/Level/Lua_Level.cpp
  trview.app/Lua/Elements/Room/Lua_Room.cpp
  trview.app/Lua/Elements/Sector/Lua_Sector.cpp
  trview.app/Lua/Elements/Sector/Lua_Sector.h
  trview.app/Lua/Elements/Trigger/Lua_Trigger.cpp
  trview.app/Lua/Lua.h
  trview.app/Lua/Lua.inl
  trview.app/Mocks/Elements/ISector.h
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
Labels: scripting

#1105 Alternate group and room for rooms
  doc/lua/room.md
  trview.app.tests/Lua/Elements/Lua_RoomTests.cpp
  trview.app/Elements/Level.cpp
  trview.app/Lua/Elements/Item/Lua_Item.cpp
  trview.app/Lua/Elements/Room/Lua_Room.cpp
  trview.app/Lua/Elements/Room/Lua_Room.h
  trview.app/Lua/Elements/Trigger/Lua_Trigger.cpp
  trview.app/Mocks/Elements/IRoom.h
Labels: scripting

#1108 Add Clear Body and Invisible flags to Lua Items
  doc/lua/item.md
  trview.app.tests/Lua/Elements/Lua_ItemTests.cpp
  trview.app/Lua/Elements/Item/Lua_Item.cpp
Labels: scripting

#1106 Console improvements
  trview.app.tests/ApplicationTests.cpp
  trview.app.tests/TestImgui.cpp
  trview.app.tests/TestImgui.h
  trview.app.tests/UI/ConsoleTests.cpp
  trview.app.tests/Windows/ConsoleManagerTests.cpp
  trview.app.tests/Windows/ConsoleTests.cpp
  trview.app.tests/trview.app.tests.vcxproj
  trview.app.tests/trview.app.tests.vcxproj.filters
  trview.app/Application.cpp
  trview.app/Application.h
  trview.app/ApplicationCreate.cpp
  trview.app/Lua/Lua.cpp
  trview.app/Mocks/Mocks.cpp
  trview.app/Mocks/UI/IViewerUI.h
  trview.app/Mocks/Windows/IConsole.h
  trview.app/Mocks/Windows/IConsoleManager.h
  trview.app/Resources/resource.h
  trview.app/Resources/trview.app.rc
  trview.app/UI/Console.cpp
  trview.app/UI/Console.h
  trview.app/UI/IViewerUI.h
  trview.app/UI/ViewerUI.cpp
  trview.app/UI/ViewerUI.h
  trview.app/Windows/Console/Console.cpp
  trview.app/Windows/Console/Console.h
  trview.app/Windows/Console/ConsoleManager.cpp
  trview.app/Windows/Console/ConsoleManager.h
  trview.app/Windows/Console/IConsole.h
  trview.app/Windows/Console/IConsoleManager.h
  trview.app/Windows/Viewer.cpp
  trview.app/Windows/Viewer.h
  trview.app/Windows/ViewerLuaRegistry.cpp
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
Labels: scripting

#1112 Add Lua bindings for Lights
  doc/lua/colour.md
  doc/lua/level.md
  doc/lua/light.md
  trview.app.tests/Lua/Elements/Lua_LevelTests.cpp
  trview.app.tests/Lua/Elements/Lua_LightTests.cpp
  trview.app.tests/Lua/Elements/Lua_RoomTests.cpp
  trview.app.tests/trview.app.tests.vcxproj
  trview.app.tests/trview.app.tests.vcxproj.filters
  trview.app/Elements/ILight.h
  trview.app/Elements/Level.cpp
  trview.app/Elements/Light.cpp
  trview.app/Elements/Light.h
  trview.app/Lua/Colour.cpp
  trview.app/Lua/Colour.h
  trview.app/Lua/Elements/Item/Lua_Item.cpp
  trview.app/Lua/Elements/Level/Lua_Level.cpp
  trview.app/Lua/Elements/Light/Lua_Light.cpp
  trview.app/Lua/Elements/Light/Lua_Light.h
  trview.app/Lua/Elements/Room/Lua_Room.cpp
  trview.app/Mocks/Elements/ILight.h
  trview.app/trview.app.vcxproj
  trview.app/trview.app.vcxproj.filters
  trview.sln
Labels: scripting

#1111 Add Lua bindings for Camera/Sink
  doc/lua/camera_sink.md
  trview.app.tests/Lua/Elements/Lua_CameraSinkTests.cpp
  trview.app.tests/Lua/Elements/Lua_LevelTests.cpp
  trview.app.tests/Lua/Elements/Lua_RoomTests.cpp
  trview.app.tests/trview.app.tests.vcxproj
  trview.app.tests/trview.app.tests.vcxproj.filters
  trview.app/Elements/CameraSink/CameraSink.cpp
  trview.app/Elements/CameraSink/CameraSink.h
  trview.app/Elements/CameraSink/ICameraSink.h
  trview.app/Elements/Level.cpp
  trview.app/Lua/Elements/CameraSink/Lua_CameraSink.cpp
  trview.app/Mocks/Elements/ICameraSink.h
Labels: scripting
